function [F,GF] = ObjFunRobust(in1,wTarget)
%OBJFUNROBUST
%    [F,GF] = OBJFUNROBUST(IN1,WTARGET)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    13-Feb-2015 08:50:27

decVar5 = in1(:,5);
decVar8 = in1(:,8);
decVar11 = in1(:,11);
decVar14 = in1(:,14);
decVar17 = in1(:,17);
decVar20 = in1(:,20);
decVar23 = in1(:,23);
decVar26 = in1(:,26);
decVar29 = in1(:,29);
decVar32 = in1(:,32);
decVar35 = in1(:,35);
decVar38 = in1(:,38);
decVar41 = in1(:,41);
decVar44 = in1(:,44);
decVar47 = in1(:,47);
decVar50 = in1(:,50);
t2 = decVar5-wTarget;
t3 = decVar8-wTarget;
t4 = decVar11-wTarget;
t5 = decVar14-wTarget;
t6 = decVar17-wTarget;
t7 = decVar20-wTarget;
t8 = decVar23-wTarget;
t9 = decVar26-wTarget;
t10 = decVar29-wTarget;
t11 = decVar32-wTarget;
t12 = decVar35-wTarget;
t13 = decVar38-wTarget;
t14 = decVar41-wTarget;
t15 = decVar44-wTarget;
t16 = decVar47-wTarget;
t17 = decVar50-wTarget;
F = t2.^2+t3.^2+t4.^2+t5.^2+t6.^2+t7.^2+t8.^2+t9.^2+t10.^2+t11.^2+t12.^2+t13.^2+t14.^2+t15.^2+t16.^2+t17.^2;
if nargout > 1
    GF = [0.0;0.0;0.0;0.0;decVar5.*2.0-wTarget.*2.0;0.0;0.0;decVar8.*2.0-wTarget.*2.0;0.0;0.0;decVar11.*2.0-wTarget.*2.0;0.0;0.0;decVar14.*2.0-wTarget.*2.0;0.0;0.0;decVar17.*2.0-wTarget.*2.0;0.0;0.0;decVar20.*2.0-wTarget.*2.0;0.0;0.0;decVar23.*2.0-wTarget.*2.0;0.0;0.0;decVar26.*2.0-wTarget.*2.0;0.0;0.0;decVar29.*2.0-wTarget.*2.0;0.0;0.0;decVar32.*2.0-wTarget.*2.0;0.0;0.0;decVar35.*2.0-wTarget.*2.0;0.0;0.0;decVar38.*2.0-wTarget.*2.0;0.0;0.0;decVar41.*2.0-wTarget.*2.0;0.0;0.0;decVar44.*2.0-wTarget.*2.0;0.0;0.0;decVar47.*2.0-wTarget.*2.0;0.0;0.0;decVar50.*2.0-wTarget.*2.0;0.0;0.0;0.0];
end
